# Generated by Django 5.0.6 on 2024-06-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_user_formdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdb',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='formdb',
            old_name='phone_number',
            new_name='phNo',
        ),
    ]
